// <auto-generated />
using System;
using FinalProjectEntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectEntityFramework.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230316133611_AddUsers")]
    partial class AddUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FinalProjectEntityFramework.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Cleaning"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Shopping"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finances"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Yardwork"
                        });
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ChoreType")
                        .HasColumnType("int");

                    b.Property<string>("ChoreUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ChoreUserId");

                    b.ToTable("Chores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ChoreType = 2,
                            ChoreUserId = "1a",
                            IsComplete = false,
                            Name = "Do dishes"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            ChoreType = 4,
                            ChoreUserId = "2a",
                            IsComplete = false,
                            Name = "Do taxes"
                        },
                        new
                        {
                            Id = 3,
                            ChoreType = 0,
                            IsComplete = false,
                            Name = "Pay ticket"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            ChoreType = 1,
                            ChoreUserId = "2a",
                            IsComplete = false,
                            Name = "Tidy the house"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            ChoreType = 3,
                            ChoreUserId = "3a",
                            IsComplete = false,
                            Name = "Vacuum house"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            ChoreType = 5,
                            ChoreUserId = "1a",
                            IsComplete = false,
                            Name = "Stock up for the year"
                        },
                        new
                        {
                            Id = 7,
                            ChoreType = 1,
                            IsComplete = false,
                            Name = "Eat dinner"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            ChoreType = 2,
                            ChoreUserId = "1a",
                            IsComplete = false,
                            Name = "Buy groceries"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            ChoreType = 4,
                            ChoreUserId = "3a",
                            IsComplete = false,
                            Name = "Shovel"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            ChoreType = 3,
                            ChoreUserId = "1a",
                            IsComplete = false,
                            Name = "Pay car insurance"
                        });
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.ChoreMonths", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("ChoreId")
                        .HasColumnType("int");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChoreId");

                    b.ToTable("ChoreMonths");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChoreId = 2,
                            Month = 0
                        },
                        new
                        {
                            Id = 2,
                            ChoreId = 2,
                            Month = 6
                        },
                        new
                        {
                            Id = 3,
                            ChoreId = 3,
                            Month = 8
                        },
                        new
                        {
                            Id = 4,
                            ChoreId = 6,
                            Month = 0
                        },
                        new
                        {
                            Id = 5,
                            ChoreId = 9,
                            Month = 0
                        },
                        new
                        {
                            Id = 6,
                            ChoreId = 9,
                            Month = 1
                        },
                        new
                        {
                            Id = 7,
                            ChoreId = 9,
                            Month = 2
                        },
                        new
                        {
                            Id = 8,
                            ChoreId = 9,
                            Month = 10
                        },
                        new
                        {
                            Id = 9,
                            ChoreId = 9,
                            Month = 11
                        });
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.ChoreUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2bf438f1-1d34-404c-9377-3626b47d97b8",
                            Email = "email@gmail.com",
                            EmailConfirmed = true,
                            FirstName = "Jaeden",
                            LastName = "Fuller",
                            LockoutEnabled = false,
                            NormalizedUserName = "EMAIL@GMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEBHWOQIzfP+5z2TosKujlDhhdJwlqK1Jf9VeMaLggOXpSPT5XKqMC/wF5gl1oohWmw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "d57ed745-b53d-4015-ae22-104b85072966",
                            TwoFactorEnabled = false,
                            UserName = "email@gmail.com"
                        },
                        new
                        {
                            Id = "2a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b1f7ebe7-95cd-497f-aff9-79b79626a390",
                            Email = "unoriginal@email.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedUserName = "UNORIGINAL@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEDVcdX4DGss1RWAwQWkV1D86jbOym3ZQltY5tDuey6Uf4QpBYCGl3ZVpX+dV0Eu2pQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3f3cc2d1-0ffb-4c69-94cf-b7c7ab622c01",
                            TwoFactorEnabled = false,
                            UserName = "unoriginal@email.com"
                        },
                        new
                        {
                            Id = "3a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "fe58968c-15d0-4867-b78f-46e9b2d22231",
                            Email = "moreunoriginal@email.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedUserName = "MOREUNORIGINAL@EMAIL.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEPjlfSV7rbweMlM5DRtAQYDcqZx6npBUMiWWOavNlF8qacXgpVyI3Z5y9JqBybvvag==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4a731897-ff1c-4c58-95ff-cb623361da98",
                            TwoFactorEnabled = false,
                            UserName = "moreunoriginal@email.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.Chore", b =>
                {
                    b.HasOne("FinalProjectEntityFramework.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("FinalProjectEntityFramework.Models.ChoreUser", "ChoreUser")
                        .WithMany()
                        .HasForeignKey("ChoreUserId");

                    b.Navigation("Category");

                    b.Navigation("ChoreUser");
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.ChoreMonths", b =>
                {
                    b.HasOne("FinalProjectEntityFramework.Models.Chore", "Chore")
                        .WithMany("ChoreMonths")
                        .HasForeignKey("ChoreId");

                    b.Navigation("Chore");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FinalProjectEntityFramework.Models.ChoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FinalProjectEntityFramework.Models.ChoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalProjectEntityFramework.Models.ChoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FinalProjectEntityFramework.Models.ChoreUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FinalProjectEntityFramework.Models.Chore", b =>
                {
                    b.Navigation("ChoreMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
